### ISSUE TITLE
Thoughts on allowing structured classes as a querystring parameter definition

### ISSUE THREAD

**Issue by DefiDebauchery** [pmateusz/meatie#70]
This may be a little too over-engineered, but felt it was worth asking. Instead of baking the list of querysting params into the method definition, would it be possible and prudent to accept a structured dataclass (including a Pydantic class) as a defined object, passing that as `query_params` (or some other argument)? 

```py
class MySearchFilter(BaseModel):
    executed: Optional[str] = None
    trusted: Optional[str] = None
    transaction_hash: Optional[str] = None
    ordering: Optional[OrderEnum]
    limit: Optional[int] = 10
    address: str
    ...
    model_config = ConfigDict(use_enum_values=True)

class MyClient(Client):
    def __init__(self, session: ClientSession, txs_url: str) -> None:
        self.base_url = txs_url  # Related to #68 

    @endpoint('/v1/search')
    async def get_search(self, query_params: MySearchFilter) -> MySearchResults
        ...
```
```py
client = MyClient(txs_url=...)

filter = MySearchFilter(executed=True, limit=5, address='0x1234')
results = await client.get_search(query_params=filter)
```

This way, the definition for the arguments remains defined, but doesn't overcomplicate the function signature.
In turn, this could make building the querystrings a little easier on end-user code, as they can modify a "`Filter`" class or similar naming convention. 

Granted, I imagine you could `**unpack` it yourself, but you'd still have to define them in the function signature, and if those options ever change, I feel I'd rather update a Filter spec than the signature, especially when you get over a few options (one API endpoint I work with has 27!).

**Comment by pmateusz** [comment]
Thank you for sharing this feature request. It is indeed something I would like to support.

I shared below the example behaviour I am considering.

```
class TimeRange:
   start: datetime.datetime
   end: datetime.datetime

def format_time_range(time_range: TimeRange) -> dict[str, Any]:
    return {"start": time_range.start.strftime("%Y-%m-%d"), "end": time_range.end.strftime("%Y-%m-%d")}

class Store(Client):
  def __init__(self) -> None:
    super().__init__(session)

   @endpoint("/api/v1/transactions")
   async def get_transactions(
      self, time_range: Annotated[TimeRange, api_ref(unwrap=format_time_range)]
   ) -> list[Any]:
            ...
  ```

**Comment by pmateusz** [comment]
The improvement is available in v0.1.12

**Comment by DefiDebauchery** [comment]
Thank you for adding based on my suggestion! I am having some trouble resolving this for my example, and I just want to make sure I'm on the right track. The parameters I'll be working with will have many different datatypes instead of the clean, specific ones you posted, so I'm hoping something generic could be used here.

Taking my original example (modified to add a datetime field to match yours)
```py
class MySearchFilter(BaseModel):
    ...
    execution_date__lte: Optional[datetime] = None
    limit: Optional[int] = 10
    address: str
    
    @field_serializer('execution_date__lte')
    def format_date(self, dt: datetime, _info):
        return dt.isoformat(timespec='seconds')
    
class MyClient(Client):
    def __init__(self, session: ClientSession, txs_url: str) -> None:
        self.base_url = txs_url

    def parse_querystring(model: BaseModel) -> dict[str, str]
        return model.model_dump(mode='json', exclude_unset=True)
        
    @endpoint('/v1/search')
    async def get_search(self, query_params: Annotated[MySearchFilter, api_ref(unwrap=parse_querystring)]) -> MySearchResults
        ...
```
```py
client = MyClient(txs_url=...)

filter = MySearchFilter(execution_date__lte: datetime.now(tz=UTC), limit=5, address='0x1234')
results = await client.get_search(query_params=filter)
```

**Comment by pmateusz** [comment]
Thank you for describing your use case in more detail. I wrote a test based on your example to confirm the library works as intended (source: https://github.com/pmateusz/meatie/blob/master/tests/examples/aiohttp/test_pydantic_query.py). Could you review it?

I don't see any issues preventing the use of more complex data types as long as they are paired with the `unwrap` method that knows how to convert them into `dict[str, Any]`, preferably `dict[str, str]`.

**Comment by DefiDebauchery** [comment]
While I admit I don't understand why this is `Annotated` with `api_ref` (and not just a direct argument pass), I can confirm this does work! 

I ended up subclassing into a `FilterModel` that has the field serializers (since all of the APIs I work with generally take dates in the same way) that also contains the static method for the unwrap. Thanks for your help.
